/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */

function fibonacci(nTermino) {
  let fibonacciNumber = [1, 1];
  for (let i = 2; i < nTermino; i++) {
    fibonacciNumber[i] = fibonacciNumber[i - 2] + fibonacciNumber[i - 1];
  }
  return fibonacciNumber;
}

function sumOfPairs(arr) {
  let arrPairs = [];
  for (let index in arr) {
    if (arr[index] % 2 == 0) arrPairs.push(arr[index]);
  }
  return arrPairs.reduce((a, b) => a + b);
}

/**
 * * caso limite el 33
 */
// console.log(fibonacci(33));

var arreglo = fibonacci(33);
console.log(sumOfPairs(arreglo));
